#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -e

if force_clean_build_enabled_for_latest_deployment; then
    echo "Force-clean builds are enabled. Recreating npm modules" 1>&2

    # Clean the npm cache. (This will clean the ~/.npm directory).
    npm cache clean
fi

#  Newer versions of Node set tmp to $HOME/tmp, which is not available
npm config set tmp $OPENSHIFT_TMP_DIR

# FIXME: Remove this line once we update NPM to latest version
npm config set ca ""

# Workaround for failure in npm install when a package in package.json
# points to a git commit.
# This issue occurs because we are running in the context of a
# git post receive-hook
unset GIT_DIR
unset GIT_WORK_TREE

if [ -f "${OPENSHIFT_REPO_DIR}"/package.json ]; then
    (cd "${OPENSHIFT_REPO_DIR}"; npm install -d)
fi
