#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -e

echo
echo "Preparing repo directory..."
echo 
# Create symlink from public to frontend/public to use as document root
ln -sf ${OPENSHIFT_REPO_DIR}frontend/public ${OPENSHIFT_REPO_DIR}public

echo
echo "Migrating storage and log directories..."
echo 
# If this is initial installation, move the default storage directory
# from official Laravel installation and remove the log directory
#
if [ ! -d ${OPENSHIFT_DATA_DIR}storage ]; then
  mv ${OPENSHIFT_REPO_DIR}frontend/app/storage ${OPENSHIFT_DATA_DIR}storage
  rm -rf ${OPENSHIFT_DATA_DIR}storage/logs
fi

# Create symlink to new storage directory location
ln -sf ${OPENSHIFT_DATA_DIR}storage   ${OPENSHIFT_REPO_DIR}frontend/app/storage

# Create a symlink to the new log directory location
ln -sf ${OPENSHIFT_LOG_DIR}   ${OPENSHIFT_DATA_DIR}storage/logs

echo 
echo "Running 'php artisan migrate --force'..."
echo 
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "php artisan migrate --force"
popd > /dev/null

echo 
echo "Running 'gulp'..."
echo 
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
echo "gulp"
popd > /dev/null